<?php
/**
 * Created by PhpStorm.
 * User: alameddincelik
 * Date: 19.05.2020
 * Time: 23:07
 */

namespace App\Util;


class SecondTasks extends ExternalTask implements TaskInterface
{
    public function __construct()
    {
        $this->url = 'http://www.mocky.io/v2/5d47f235330000623fa3ebf7';
        $this->mappingArray = [
            'estimated_duration' => 'duration',
            'level' => 'level',
        ];
        parent::__construct($this->url);
    }

    protected function fetchTasks()
    {
        return parent::fetchTasks();
    }

    protected function filterTasks()
    {
        parent::filterTasks();
        $responseArray = [];
        foreach ($this->response as $item) {
            foreach (array_values($item)[0] as $key => $value) {
                $tempArray[$this->mappingArray[$key]] = $value;
            }
            $tempArray['id'] = key($item);
            array_push($responseArray, $tempArray);
        }
        $this->response = $responseArray;
        return $this;
    }

    public function getResponse()
    {
        return parent::getResponse(); // TODO: Change the autogenerated stub
    }
}